_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.8.10
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
env_name:
    value: ClutteredScene
